CREATE TABLE therapist (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE patient (
  PID INT PRIMARY KEY NOT NULL,
  TherapistID INT FOREIGN KEY NOT NULL,
  Pass VARCHAR(255) NOT NULL,
  Username VARCHAR(255) NOT NULL UNIQUE,
  HAKey INT FOREIGN KEY NOT NULL
);

